name: Run EVE Price Scraper Hourly

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eve_prices_and_analysis
          path: |
            local_prices/fuel
            local_prices/minerals
            local_prices/doctrine
            analysis/fuel
            analysis/minerals
            trade/fuel
            trade/minerals
            trade/doctrine
            commodities_indices/prices
            commodities_indices/plots

      - name: Commit and push updated prices
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add local_prices/fuel local_prices/minerals local_prices/doctrine
          git add analysis/fuel analysis/minerals
          git add trade/fuel trade/minerals trade/doctrine
          git add commodities_indices/prices commodities_indices/plots

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update EVE market data, indices, and plots (v0.1.3) [skip ci]"
            git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git
            git push origin master
          else
            echo "No changes to commit"
          fi